[package]
name = "talos-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.talos]
path = ".."

[[bin]]
name = "fuzz_encrypt_decrypt"
path = "fuzz_targets/fuzz_encrypt_decrypt.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_bitwise"
path = "fuzz_targets/fuzz_bitwise.rs"
test = false
doc = false
bench = false
